### ISSUE TITLE
Tracking features for next iteration of Restore-DbaDatabase

### ISSUE THREAD

**Issue by Stuart-Moore** [sqlcollaborative/dbatools#1201]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

A place to keep track of things people would like adding to the Restore-DbaDatabase functionality in the next iteration.

So far I've got (Ticked means I've got it working):
 - [x] IgnoreLogBackup will now make MaintenanceSolution skip the Log folder as well for extra speed
 - [x] DirectoryRecurse switch to make Directory filter recurse
 - [x] Standby is now an option for a restored db
 - [x] Restore from Azure support (Backups and Headers done)
 - [x] Continue restore on a db in recovery or standby modes
 - [ ] Potentially an option to allow fast and loose restores for log files (not convinced it's a great idea, but people seem to like the idea)

Anything else people would like?

**Comment by galador** [comment]
It would be nice if there was a switch that if you pass something to `DatabaseName`, it would auto-rename the log and datafiles.

For example, if I want to restore `AdventureWorks` to `AdventureWorks_Restore` on the same server, it would be nice to rename the physical files to something like `AdventureWorks_Restore.mdf` and `AdventureWorks_Restore_log.ldf`.

I could set `DestinationFilePrefix` to the new database name, but then if the datafile of the original database was called `AdventureWorks.mdf`, it would name it `AdventureWorks_RestoreAdventureWorks.mdf`, which isn't very pretty. :)

Maybe I could make it work with FileMapping, but then I think I would have to know what the logical names & default file path are in advance, and I'm trying to write up something fairly generic that I could re-use.

**Comment by Stuart-Moore** [comment]
How would you want it to handle multiple datafiles or logfiles? That's the
bit I couldn't come up with a decent plan for. Appending an id number is
one option, but how do we get them in the 'right' order for all users?

**Comment by Zhunya** [comment]
I see than @galador asked for things how SSMS do in restores, I want this too, and going to make my own branch for this naming behavior.

How SSMS do when you have more than 1 data file? 
just adds ```**_x**``` (where **x** is 0...n)to file names starting with second data file

**Comment by Zhunya** [comment]
My backlog for Restore-DbaDatabase:
- do restores as in this issue, this behavior is essential for many of us
- having prefixes and suffixes for database names and/or files

### template for names
- restoring database with name $prefix$DatabaseName$suffix
- changing data and log names to [$prefix]$Databasename[$suffix][$FileNumber].[mdf|ndf|ldf] if corresponding paramaters specified to command

**Comment by galador** [comment]
Yes, basically if there was an option to handle the file renames like SSMS (which is to say, basically replace any instance of `OldDatabaseName` with `NewDatabaseName`), e.g.:

![image](https://cloud.githubusercontent.com/assets/52107/26202471/2dcdeea4-3b9d-11e7-91f4-8e66d5219ee5.png)

This example is renaming `AdventureWorks2012` to `AdventureWorks`.

**Comment by Zhunya** [comment]
From Slack: add support to restore database `with keep_cdc`

**Comment by Stuart-Moore** [comment]
keep_cdc is one of the few things they haven't surfaced in SMO atm. It can be done by getting the T-SQL and injecting it back in, but it's a bit of a hack as we'd then have to passed it back in via Invoke-DbaSqlCmd, so we'd also end up with a different output to other restores

**Comment by Stuart-Moore** [comment]
Continue works with file based restores, Get-DbaBackupHistory needs some more work for that bit to work properly, and don't want to drag too many files into this PR.

Going to do a merge of dev to see how much work that's going to cause, and then I'll work on the renaming options

**Comment by Stuart-Moore** [comment]
PR 1304 just done in
These features in:
IgnoreLogBackup will now make MaintenanceSolution skip the Log folder as well for extra speed
 DirectoryRecurse switch to make Directory filter recurse
 Standby is now an option for a restored db
 Continue restore on a db in recovery or standby modes

Will add the others in a bit, keeping a branch out for too long is a bit problematic these days

**Comment by Stuart-Moore** [comment]
Just pushing up a new PR with these features:

Restore from Azure
DestinationFileSuffix
Replace dbname in filename

**Comment by Stuart-Moore** [comment]
Really, really not convinced about the auto numbering of files during restore being a good idea. SSMS only does that during file creation not restores.

Mainly because files can appear and disappear during restores. It's a logged operation so it 'happens' during the restore (SQL doesn't just go from A-Z, it goes via B,C,D,E, etc and if C means it adds 3 files it adds 3 files, then removes 2 at E and puts 3 more back at Q)

So we could scan all the filelists at the start of the restore and work it out. But then how do we tell if
Data1 -> C:\data\data_1.mdf at point C
is the same as
Data1 -> e:\data\data_1.mdf  at point M,
could have been moved, or it could have been dropped and recreated?

How do we decided the file ordering for numbering? Alphabetically, by size, by type? Each one will be wrong for someone if we try to preempt it. And any of those orderings could change the next time they run the restore.

If someone really wants to do that, they have 2 options to get it done properly:

1. Name their files upon creation wit x_of_y and stick with prefix and folders
2. Write a filemapping hash and push it in

If someone want to have a go they can, but I'll put money on the fact I can break it without too much trouble.

My aim with the restore stuff is reliability and repeatability over anything else.

**Comment by Stuart-Moore** [comment]
It's not pretty (ie T-SQL hack) but CDC is now in -  https://github.com/sqlcollaborative/dbatools/tree/restorecdc

If anyone who actually uses CDC is reading this, take it for a spin please.

**Comment by TheRockStarDBA** [comment]
I get 404 error. We are using CDC and service broker. Would love to have this.

**Comment by niphlod** [comment]
@TheRockStarDBA : it's been already committed to the repo, CDC should work fine

**Comment by Stuart-Moore** [comment]
All of these are in now in some form or another. Will close this and let newer requests filter in in their own issues
