### ISSUE TITLE
Copy-DbaSsisCatalog - ToDo List

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2112]
Updates/modifications needed for Copy-DbaSsisCatalog: on-going list of things as I find them to fix on this command

- [ ] Add Windows Credential support for service verification? (current logic checks to see if SSIS service is running, this utilizes WMI/CIM to check the service; alternative would be validate if SSIS is on the host via DMV/system catalog views maybe `sys.dm_server_services`).
- [ ] ...

**Comment by BartekR** [comment]
I would add:

- [ ] Copy encrypted variables
- [ ] Copy environment references

**Comment by wsmelton** [comment]
We do that in the Get command if I recall, ref encrypted values. Which the issue with that get command is it is/was decrypting the values to display. Can you copy the encrypted values without having to decrypt them @BartekR ? (Note I've never tried.)

**Comment by BartekR** [comment]
I don't think you can copy encrypted values, as they are encrypted using a certificate and symmetric key for the environment, and the certificate is encrypted using database master key, but I will do some testing to be sure.

**Comment by wsmelton** [comment]
Well if it requires decrypting to pull out I'd be against doing that one via PS.

I would think best option to copying items like that would be to just move the database and then copy the certificates overs so no decryption is required. That is the MS supported method at least.

**Comment by janeztr** [comment]
As mentioned above: project to environment(s) references are not copied.
But the same goes for project parameter references to environment variables. 
Both can be set via Microsoft.SqlServer.Management.IntegrationServices  ProjectInfo class (References.Add(), Parameters[].Set())
