### ISSUE TITLE
dbatools 1.0 todo

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4457]
February 14, 2019 is my goal 💝 This will be updated as I remember what it is I wanted in here.

### Feature complete

- [x] Find-DbaInstance
- [x] Log Shipping 
- [x] Mirroring
- [x] Availability Groups
- [x] Export whole instance
- [ ] Install-DbaInstance
- [x] Update-DbaInstance
- [x] DBCC Support
- [x] New-DbaDatabase 1.0 (Simplified is fine, perhaps we can resurrect that old PR)
- [x] Data masking /cc @sanderstad 
- [ ] Firewall commands

#### Bugs

- [x] CM fixes 
- [x] Messaging fixes
- [ ] Other [bugs](https://github.com/sqlcollaborative/dbatools/issues?q=is%3Aissue+is%3Aopen+label%3Abugs_life) (currently 88 open)

### Other

- [x]  Breaking changes and enhancements to Start-DbaMigration
- [ ]  Remove vast majority of aliases but keep command that does rename
- [ ]  That includes all parameter aliases 👎 
- [ ] Reevaluate disabled appveyor tests and see what we can make work
- [x] Make Copy command names match the rest. like DbMail and XESession
- [x] Remove all unneeded instances of $collection

**Comment by sqllensman** [comment]
I would be happy to complete the missing DBCC commands. Do you want an issue raised or is there an existing issue?

**Comment by potatoqualitee** [comment]
awesome! i'd love that. i don't believe ive had any issues. can you propose the design(s)? I was gonna look thru the SMO options

for example
`$db.CheckTables([Microsoft.SqlServer.Management.Smo.RepairType]::None)`

**Comment by potatoqualitee** [comment]
i like this consolidated list, gonna keep it open for now

**Comment by potatoqualitee** [comment]
good point, bot! these are all moved
